---
- name: .:(RHEL):. upgrade kubelet binary to the next version
  yum:
    name: "kubelet-{{k8s_next_version}}"
    state: present
    update_cache: yes


- name: .:(RHEL):. daemon reload and restart kubelet service
  systemd:
    name: kubelet
    state: restarted
    daemon_reload: yes


- name: .:(RHEL):. upgrade kubectl binary to the next version
  yum:
    name: "kubectl-{{k8s_next_version}}"
    state: present
    update_cache: yes
