- name: .:(RHEL):. removing previous proxy from yum.conf
  replace:
    path: /etc/yum.conf
    regexp: '^(proxy=.*)$'
    replace: '#\1'


- name: .(RHEL):. adding new proxy to yum.conf
  lineinfile:
    path: /etc/yum.conf
    line: "proxy={{proxy_url}}"
    create: yes
    state: present


- name: .:(RHEL):. creating docker proxy file
  file:
    path: /etc/systemd/system/docker.service.d/
    state: directory
    mode: '0755'
    

- name: .:(RHEL):.setting proxy for docker
  template:
    src: templates/proxy_conf.j2
    dest: /etc/systemd/system/docker.service.d/proxy.conf 
    force: yes
